spring.application.name=missions
# DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/missions_ocp
spring.datasource.username=postgres
spring.datasource.password=0000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logs pour déboguer Spring Security et l'application
logging.level.org.springframework.security=DEBUG
logging.level.com.ocp.missions=DEBUG